---
- name: Setting up server with Apache HTTP Server
  hosts: apache-servers
  become: true
  vars:
    packages:
      - name: apache2
        required: True
      - name: apt-transport-https
        required: True
      - name: wget
        required: True
  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes
        
    - name: Install Apache and other packages
      apt:
        name: "{{ item.name }}"
        state: present
      when: item.required == True 
      loop: "{{ packages }}"
      
    - name: Start Apache
      service:
        name: apache2
        state: started

