#################################################################################################
# This deployment is based on Ubuntu 18.04 running NGINX 1.14.0
# The installation of the Signal Sciences module on NGINX is based on the Ubuntu distribution
#################################################################################################

---
- name: Deploying Signal Sciences to NGINX Servers
  hosts: nginx-servers
  become: true
  vars_files:
    - ../vars/keys.yml
  vars:
    packages:
      - name: sigsci-agent
        required: True
      - name: nginx-extras
        required: True
      - name: sigsci-module-nginx
        required: True
  tasks:
    - name: Add SigSci Package Repositories on Ubuntu 18.04
      apt_key:
        url: https://apt.signalsciences.net/gpg.key
        state: present
      when: ansible_os_family == "Ubuntu" and ansible_distribution_version == "18.04"

    - name: Adding SigSci repo on Ubuntu 18.04
      apt_repository:
        repo: deb https://apt.signalsciences.net/release/ubuntu/ bionic main
        state: present
      when: ansible_os_family == "Ubuntu" and ansible_distribution_version == "18.04"

    - name: Run apt-get update again
      apt:
        update_cache: yes

    - name: Installing SigSci Agent
      apt:
        name: "{{ item.name }}"
        state: present
      when: item.required == True
      loop: "{{ packages }}"

    - name: Create SigSci directory
      file:
        path: "/etc/sigsci/"
        state: directory

    - name: Create agent.conf file
      file:
        path: "/etc/sigsci/agent.conf"
        state: touch

    - name: Insert agent keys
      blockinfile:
        path: "/etc/sigsci/agent.conf"
        block: |
               accesskeyid= {{ agent_access_key }}
               secretaccesskey= {{ agent_secret_key }}

    - name: Start SigSci Agent
      service:
        name: sigsci-agent
        state: started

    - name: Insert include statemnt in nginx.conf
      blockinfile:
        path: "/etc/nginx/nginx.conf"
        marker: "# {mark} SIGSCI BLOCK #"
        insertafter: "http {"
        block: |
          include "/opt/sigsci/nginx/sigsci.conf";

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

    - name: Send GET Request
      uri:
        url: http://localhost
        method: GET
