---
  - name: Provision an EC2 Instance
    hosts: local
    connection: local
    gather_facts: True
    tags: provisioning
    
    #The vars need to be filled out before running the ansible playbook. Be sure to fill in the information in brackets (remove brackets after entering your values)
    vars:
            instance_type: t2.micro #Specify the instance type
            security_group: [Insert your security group here] #Insert applicable security groups here
            image: ami-18726478 #AWS AMI used to build EC2 instance, this one is for RHEL7
            keypair: [Your AWS Keypair] #Keypair created in AWS
            region: [Your AWS Region] #Set to desired region
            access_key: [Your AWS Access Key] #AWS Access Key
            secret_key: [Your AWS Secret Key] #AWS Secret Key
            count: 1 #Enter the number of instances you want to launch

    tasks:
            - name: Launch the new EC2 Instance
              ec2:
                      aws_access_key={{ access_key }}
                      aws_secret_key={{ secret_key }}
                      group={{ security_group }} 
                      instance_type={{ instance_type}}
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
              register: ec2

            - name: Add the newly created EC2 instance(s) to the local host group 
              lineinfile:
                      dest="./hosts"
                      regexp={{ item.public_ip }}
                      insertafter="[apache-servers]" line={{ item.public_ip}}
              with_items: "{{ ec2.instances }}"
            
            - name: Wait for SSH to come up
              wait_for: 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
              with_items: "{{ ec2.instances }}"

            - name: Tag Instance
              ec2_tag:
                      aws_access_key={{ access_key }}
                      aws_secret_key={{ secret_key }}
                      resource={{ item.id }}
                      region={{ region }}
                      state=present
              with_items: "{{ ec2.instances }}"
              args:
                      tags:
                              Name: rhel-apache #Adds name tag to instance
