---
- name: Deploying Signal Sciences to Apache Servers
  hosts: apache-servers
  become: true
  vars_files:
    - ../../ansible-playbooks/vars/keys.yml
  tasks:
    - name: Add SigSci Package Repositories on CentOS7
      file:
        path: "/etc/yum.repos.d/sigsci.repo"
        state: touch
      when: ansible_os_family == "RedHat" and ansible_distribution_version == "7"
    - name: Adding SigSci repo on CentOS7
      blockinfile:
        path: /etc/yum.repos.d/sigsci.repo
        block: |
               [sigsci_release]
               name=sigsci_release
               baseurl=https://yum.signalsciences.net/release/el/7/$basearch
               repo_gpgcheck=1
               gpgcheck=0
               enabled=1
               gpgkey=https://yum.signalsciences.net/release/gpgkey
               sslverify=1
               sslcacert=/etc/pki/tls/certs/ca-bundle.crt
      when: ansible_os_family == "RedHat" and ansible_distribution_version == "7"
    - name: Run yum update
      yum:
        name: "*"
        state: latest
    - name: Installing SigSci Agent
      yum:
        name: sigsci-agent
        state: present
    - name: Create SigSci directory
      file:
        path: "/etc/sigsci/"
        state: directory
    - name: Create agent.conf file
      file:
        path: "/etc/sigsci/agent.conf"
        state: touch
    - name: Insert agent keys
      blockinfile:
        path: "/etc/sigsci/agent.conf"
        block: |
               accesskeyid= {{ agent_access_key }}
               secretaccesskey= {{ agent_secret_key }}
    - name: Start SigSci Agent
      service:
        name: sigsci-agent
        state: started
    - name: Install SigSci Apache Module
      yum:
        name: sigsci-module-apache
        state: present
    - name: Update httpd configuration
      blockinfile:
        path: "/etc/httpd/conf/httpd.conf"
        marker: "# {mark} SIGSCI BLOCK #"
        insertafter: 'IncludeOptional conf.d/*.conf'
        block: |
          'LoadModule signalsciences_module /etc/httpd/modules/mod_signalsciences.so'
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
